"""Nightly maintenance run (README: 06:00-07:00 SGT, after US market close).

Invoked as `python -m app.jobs.nightly` by the k8s CronJob. Deliberately a
batch entrypoint talking to the DB directly rather than an HTTP endpoint the
cron curls: a full run is a yfinance call per ticker, a trafilatura article
download per news item, and an LLM call per ticker, which takes minutes and
would exceed any sane request timeout while occupying a uvicorn worker.

Every step is isolated — one flaky ticker must not abort the rest of the run —
and the whole run is idempotent, so the Job's retry is safe: price/fx writes
upsert, news writes ignore conflicts, and summaries hit their per-(target,date)
cache rather than regenerating (and re-billing) on a second pass.
"""

import logging
import sys
from datetime import date
from typing import Any, Callable

from app.core.config import settings
from app.db import database
from app.services.fx import refresh_fx_rates
from app.services.holdings import list_tracked_tickers
from app.services.market_data import refresh_price_history
from app.services.news import refresh_news
from app.services.summaries import get_or_generate_summary

logger = logging.getLogger("nightly")


def _step(failures: list[str], label: str, fn: Callable[..., Any], *args: Any) -> bool:
    """Runs one unit of work, recording rather than raising on failure.
    Returns True if it succeeded.

    Catches bare Exception on purpose: the services raise their own typed
    errors, but yfinance/trafilatura/the LLM SDKs can surface anything from a
    socket timeout to a parse error, and none of that should cost us the
    remaining tickers.
    """
    try:
        result = fn(*args)
    except Exception as exc:
        logger.error("%-28s FAILED  %s: %s", label, type(exc).__name__, exc)
        failures.append(label)
        return False
    logger.info("%-28s ok      %s", label, result if result is not None else "")
    return True


def _prewarm(target_type: str, ticker: str, as_of: date) -> Any:
    """Summary generation for the nightly run specifically. cache_without_news=True
    because this runs *after* the news fetch above: an empty feed here means the
    ticker genuinely had no news today, so that answer is worth caching rather than
    being regenerated by every page view for the rest of the day.
    """
    return get_or_generate_summary(target_type, ticker, as_of, cache_without_news=True)


def run_nightly(as_of: date | None = None) -> int:
    """Returns a process exit code: 0 if every step succeeded, 1 otherwise."""
    as_of = as_of or date.today()
    failures: list[str] = []

    tickers = list_tracked_tickers()
    logger.info("Nightly run for %s — %d tracked ticker(s): %s",
                as_of, len(tickers), ", ".join(tickers) or "(none)")

    # fx / prices / news are mutually independent — three different tables, none of
    # them reading another — so their order among themselves is arbitrary. There is no
    # separate "convert to SGD" step to sequence: no model stores an SGD value, it's
    # computed as quantity * price * fx on every read.
    fx_ok = _step(failures, "fx-rates", refresh_fx_rates)

    stale: set[str] = set()
    for ticker in tickers:
        if not _step(failures, f"price:{ticker}", refresh_price_history, ticker):
            stale.add(ticker)
    for ticker in tickers:
        if not _step(failures, f"news:{ticker}", refresh_news, ticker):
            stale.add(ticker)

    # Summaries MUST come last: they read the prices and fx (via get_portfolio) and the
    # news written above. Running one over incomplete inputs fails silently rather than
    # loudly — a missing fx rate makes portfolio.py skip that holding, and missing news
    # feeds the prompt "(no recent news available)" — and since a Summary row is never
    # overwritten, that degraded answer would be cached for this date permanently.
    # So a ticker whose inputs failed is skipped entirely: /api/summary's on-demand
    # fallback will generate it properly on first view, once the data is actually there.
    if settings.summary_prewarm:
        for ticker in tickers:
            if ticker in stale:
                logger.warning("%-28s skipped — its inputs failed this run", f"summary:{ticker}")
                continue
            _step(failures, f"summary:{ticker}", _prewarm, "stock", ticker, as_of)

        # The portfolio summary reads every holding's position and news, so any one
        # ticker being stale is enough to make it not worth caching.
        if fx_ok and not stale:
            _step(failures, "summary:portfolio", _prewarm, "portfolio", "", as_of)
        else:
            logger.warning("%-28s skipped — it reads every ticker, and some inputs failed this run",
                           "summary:portfolio")
    else:
        logger.info("Summary pre-warm disabled (SUMMARY_PREWARM=false) — /api/summary generates on demand")

    if failures:
        logger.error("Nightly run finished with %d failure(s): %s", len(failures), ", ".join(failures))
        return 1

    logger.info("Nightly run finished cleanly")
    return 0


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)-5s %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    database.connect(reuse_if_open=True)
    try:
        exit_code = run_nightly()
    finally:
        if not database.is_closed():
            database.close()
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
